### ISSUE TITLE
IndexError: cannot do a non-empty take from an empty axes.

### ISSUE THREAD

**Issue by muzizhi** [zju3dv/eval-vislam#6]
when I try to run my result,it seems to have some issues:
I run:python3 ismar-score.py --round 0 --is_vislam 0 --trajectory_base_dir ~/the/MY-SLAM/ --gt_base_dir ~/the/Data
and the MY-SLAM/ is just trajectory file folders
and this is the error(specific):
Traceback (most recent call last):
  File "ismar-score.py", line 72, in <module>
    trajectory_base_dir + '/' + seq_name)
  File "ismar-score.py", line 39, in select_round
    return ape_list.index(np.percentile(ape_list, 50, interpolation='nearest'))
  File "/home/cgnerds/anaconda3/envs/demo6/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3707, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)
  File "/home/cgnerds/anaconda3/envs/demo6/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3826, in _quantile_unchecked
    interpolation=interpolation)
  File "/home/cgnerds/anaconda3/envs/demo6/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3405, in _ureduce
    r = func(a, **kwargs)
  File "/home/cgnerds/anaconda3/envs/demo6/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3908, in _quantile_ureduce_func
    r = take(ap, indices, axis=axis, out=out)
  File "/home/cgnerds/anaconda3/envs/demo6/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 189, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/home/cgnerds/anaconda3/envs/demo6/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.

I need some help,where is wrong?

**Comment by ybbbbt** [comment]
Maybe there is something wrong with `select_round` in `ismar-score.py`. Can you please try `./bin/accuracy` at first? If this is ok, you can send trajectory folder to challenge_chairs@ismar19.org, and I will try to figure out the problem.
Currently, `ismar-score.py` is a prototype of overall scoring, which may not be able to handle incorrect inputs.

**Comment by muzizhi** [comment]
I just try ./accuracy. it can get some result and it seems that it has no problem.
but my pose file is wrong,the file are the poses after final global optimization,so I have to change it now.
I don't know if it will cause this issue,or just have other reasons.
I will try it again when I get right poses
thanks!
